jscomps_manifestdir=$(libdir)/mozembedlite-next153/components
jscomps_manifest_DATA = \
	EmbedLiteJSComponents.manifest \
	AboutRedirector.sys.mjs \
	LoginManagerPrompter.sys.mjs \
	HelperAppDialog.sys.mjs \
	EmbedPrefService.sys.mjs \
	FilePicker.js \
	ContentPermissionPrompt.sys.mjs \
	ContentPermissionManager.sys.mjs \
	EmbedLiteGlobalHelper.sys.mjs \
	EmbedLiteConsoleListener.sys.mjs \
	EmbedLiteDevTools.sys.mjs \
	EmbedLiteAddons.sys.mjs \
	EmbedLiteAddonsHandler.sys.mjs \
	extensions/ext-browserAction.js \
	extensions/ext-tabsStub.js \
	schemas/tabs.json \
	extensions/ext-browserActionChild.js \
	extensions/ext-embedliteChild.js \
	extensions/ext-embedlite.json \
	EmbedLiteAlertsService.sys.mjs \
	EmbedLiteChromeManager.sys.mjs \
	EmbedLiteOrientationChangeHandler.sys.mjs \
	EmbedLiteSyncService.js \
	EmbedLiteFaviconService.sys.mjs \
	EmbedLiteSearchEngine.sys.mjs \
	EmbedLiteErrorPageHandler.sys.mjs \
	UserAgentOverrideHelper.sys.mjs \
	XPIDialogService.sys.mjs \
	PrivateDataManager.sys.mjs \
	EmbedliteDownloadManager.sys.mjs \
	LoginsHelper.sys.mjs \
	EmbedLiteWebrtcUI.sys.mjs \
	IntentProtocolHandler.sys.mjs \
	$(NULL)

AM_CPPFLAGS = $(DEPS_CFLAGS)
